# Generated by Django 3.0.6 on 2020-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splanerapp', '0004_auto_20200608_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(default='rgb (255, 255, 255)', max_length=24),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name=''),
        ),
    ]
